app: telegram-dm-bot
services:
  - name: bot
    ports:
      - port: 8080
        protocol: http
    env:
      - name: API_ID
        secret: true
      - name: API_HASH
        secret: true
      - name: TELEGRAM_BOT_TOKEN
        secret: true
      - name: DAILYMOTION_API_KEY
        secret: true
      - name: DAILYMOTION_API_SECRET
        secret: true
      - name: DAILYMOTION_USERNAME
        secret: true
      - name: DAILYMOTION_PASSWORD
        secret: true
    regions:
      - fra
    docker:
      build:
        dockerfile: Dockerfile
