app: telegram-dm-bot
services:
  - name: bot
    ports:
      - port: 8080
        protocol: http
    env:
      - name: API_ID
        secret: true
      - name: API_HASH
        secret: true
      - name: TELEGRAM_BOT_TOKEN
        secret: true
      - name: DAILYMOTION_API_KEY
        secret: true
      - name: DAILYMOTION_API_SECRET
        secret: true
      - name: DAILYMOTION_USERNAME
        secret: true
      - name: DAILYMOTION_PASSWORD
        secret: true
    regions:
      - fra
    scalings:
      min: 1
      max: 1
    docker:
      build:
        dockerfile: Dockerfile
    http_health_check:
      path: /
      port: 8080
      interval: 10
      timeout: 5
      unhealthy_threshold: 3
      healthy_threshold: 2
